apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  template:
    metadata:
      name: nginx-template
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-deployment
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
#      restartPolicy: Always
  selector:
    matchLabels:
      app: nginx

