server:
  port: 8080
spring:
  application:
    name: sky-client-service
eureka:
  instance:
    appname: sky-client
    lease-renewal-interval-in-seconds: 5 # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 10 # 发呆时间，即服务续约到期时间（缺省为90s）
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}:@project.version@ #可以不配置，默认为ip:port。@引用maven里的属性
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7777/eureka/ # 注册到eureka中心，获取到配置服务
    healthcheck:
      enabled: true # 开启健康检查（依赖spring-boot-starter-actuator）
service-url:
  user-service: http://user-service