server:
  port: 8080
spring:
  application:
    name: sky-client

# eureka配置
eureka:
  instance:
    appname: sky-client-eureka # 默认是spring.application.name字段。在eureka配置中心看到的"Instances currently registered with Eureka"里的Application字段
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}:@project.version@ #可以不配置，默认为ip:port。@引用maven里的属性。在eureka配置中心看到的"Instances currently registered with Eureka"里的status字段
    lease-renewal-interval-in-seconds: 5 # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 10 # 发呆时间，即服务续约到期时间（缺省为90s）
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8000/eureka/ # 注册到eureka中心，获取到配置服务
    healthcheck:
      enabled: true # 开启健康检查（依赖spring-boot-starter-actuator）
service-in-eureka: #自定义的key，为了引用注册到eureka里的远程服务
  sky-server: http://sky-server # 对应远程服务的spring.application.name属性值

# feign和ribbon结合配置
sky-server: #注册到eureka里的远程服务名。对应远程服务的spring.application.name属性值
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule # 指定策略。feign默认的是轮询的策略，这里的配置可以自定义

#参考文档：https://docs.spring.io/spring-boot/docs/1.4.7.RELEASE/reference/htmlsingle/#boot-features-logging 26章
#参考代码：见spring-boot-1.5.8包里的org.springframework.boot.logging.log4j2、org.springframework.boot.logging.logback、org.springframework.boot.logging.java等
#可切换成log4j2：显式切换日志组件，默认是logback，logback的配置文件在spring发行包里是自带的，可以使用属性或者xml文件调整logback的配置
#log4j2的日志级别会被这个配置文件里的debug属性覆盖
#日志
logging:
#  config: classpath:log4j2.xml
#  config: classpath:log4j2-file.xml
#  config: classpath:org/springframework/boot/logging/logback/base.xml
  #日志配置文件位置
  # 官方推荐使用的xml名字的格式为：logback-spring.xml而不是logback.xml，至于为什么，因为带spring后缀的可以使用<springProfile>这个标签
  config: classpath:log/logback-spring.xml
  #日志打印位置，这里是默认在当前项目根路径下
  path: log