server:
#  port: ${random.int[8083,8089]} # 随机范围端口（在eureka里有bug，注册到eureka里的端口是错的）。跳过8081，The Tomcat connector configured to listen on port 8081 failed to start
  port: 8081 # 如果要起多个服务端，可以启动时，命令行指定不同的端口
spring:
  application:
    name: sky-server
eureka:
  instance:
    appname: sky-server-eureka
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}:@project.version@ #可以不配置，默认为ip:port。@引用maven里的属性
    lease-renewal-interval-in-seconds: 5 # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 10 # 发呆时间，即服务续约到期时间（缺省为90s）
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8000/eureka/ # 注册到eureka中心，获取到配置服务
    healthcheck:
      enabled: true # 开启健康检查（依赖spring-boot-starter-actuator）